SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/EBizcharge_Setting__c.object-meta.xml
<CustomObject>
    <label>EBizcharge Setting</label>
    <nameField>
        <label>EBizcharge Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBizcharge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFQBD/Ebiz/force-app/main/default/objects/Order/fields/EBizCharge_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>EBizCharge_Internal_ID__c</fullName>
    <label>EBizCharge Internal ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SFQBD/Ebiz/force-app/main/default/classes/test_ebc_OrderInsertOrUpdateApexFlow.cls
@isTest
public with sharing class test_ebc_OrderInsertOrUpdateApexFlow {
    @isTest(OnInstall = true)
    public static void testMethod1() {
        DML dml = (DML) MockUtil.createMock(DML.class);
        List < Order > orderList = StaticMockData.getOrder();
        orderList[0].EBizCharge_Internal_ID__c = '111111';
        orderList[1].EBizCharge_Internal_ID__c = null;
        EBizcharge_Setting__c ES = StaticMockData.getEBizcharge_Setting()[0];
        OrderInsertOrUpdateApexFlow.invoke_updateOrder(orderList);
        OrderInsertOrUpdateApexFlow.invoke_AddOrderFuture('000111111');
    }
}