SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/EBizcharge_Setting__c.object-meta.xml
<CustomObject>
    <label>EBizcharge Setting</label>
    <nameField>
        <label>EBizcharge Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBizcharge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFQBD/Ebiz/force-app/main/default/objects/Opportunity/fields/EBizCharge_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>EBizCharge_Internal_ID__c</fullName>
    <label>EBizCharge Internal ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SFQBD/Ebiz/force-app/main/default/classes/test_OpportunityInsertUpdateFlow.cls
@isTest
public with sharing class test_OpportunityInsertUpdateFlow {
    public static testMethod void testMethod1() {
        DML dml = (DML) MockUtil.createMock(DML.class);
        List < opportunity > opportunityList = StaticMockData.getOpportunity();
        opportunityList[0].EBizCharge_Internal_ID__c = '111111111';
        opportunityList[1].EBizCharge_Internal_ID__c = null;
        EBizcharge_Setting__c ES = StaticMockData.getEBizcharge_Setting()[0];
        OpportunityInsertOrUpdateApexFlow.invoke_updateOpportunity(opportunityList);
        OpportunityInsertOrUpdateApexFlow.invoke_AddOpportunityFuture('111111111'); //System.AuraHandledException: Script-thrown exception
    }
}