SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/EBizcharge_Setting__c.object-meta.xml
<CustomObject>
    <label>EBizcharge Setting</label>
    <nameField>
        <label>EBizcharge Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBizcharge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <label>Application ID</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>b31d6acb-c2d7-4c37-80c7-d663b1b008ed</fullName>
                <default>true</default>
                <label>b31d6acb-c2d7-4c37-80c7-d663b1b008ed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Auto_Upload_Account__c.field-meta.xml
<CustomField>
    <fullName>Auto_Upload_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If value true, Account will auto upload on gateway upon creation or modification</description>
    <inlineHelpText>If value true, Account will auto upload on gateway upon creation or modification</inlineHelpText>
    <label>Auto Upload Account</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Auto_Upload_Contact__c.field-meta.xml
<CustomField>
    <fullName>Auto_Upload_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Upload Contact</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Auto_Upload_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Auto_Upload_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Upload Opportunity</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Auto_Upload_Order__c.field-meta.xml
<CustomField>
    <fullName>Auto_Upload_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If value true, Order will upload on gateway upon creation or modification</description>
    <inlineHelpText>If value true, Order will upload on gateway upon creation or modification</inlineHelpText>
    <label>Auto Upload Order</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Auto_Upload_Quote__c.field-meta.xml
<CustomField>
    <fullName>Auto_Upload_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Upload Quote</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/AutoPay_annually__c.field-meta.xml
<CustomField>
    <fullName>AutoPay_annually__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AutoPay annually</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/AutoPay_bi_annually__c.field-meta.xml
<CustomField>
    <fullName>AutoPay_bi_annually__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AutoPay bi annually</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/AutoPay_bi_monthly__c.field-meta.xml
<CustomField>
    <fullName>AutoPay_bi_monthly__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AutoPay bi monthly</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/AutoPay_bi_weekly__c.field-meta.xml
<CustomField>
    <fullName>AutoPay_bi_weekly__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AutoPay bi weekly</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/AutoPay_daily__c.field-meta.xml
<CustomField>
    <fullName>AutoPay_daily__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AutoPay daily</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/AutoPay_four_week__c.field-meta.xml
<CustomField>
    <fullName>AutoPay_four_week__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AutoPay four week</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/AutoPay_monthly__c.field-meta.xml
<CustomField>
    <fullName>AutoPay_monthly__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AutoPay monthly</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/AutoPay_quarterly__c.field-meta.xml
<CustomField>
    <fullName>AutoPay_quarterly__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AutoPay quarterly</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/AutoPay_weekly__c.field-meta.xml
<CustomField>
    <fullName>AutoPay_weekly__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AutoPay weekly</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Data_Flow_Direction__c.field-meta.xml
<CustomField>
    <fullName>Data_Flow_Direction__c</fullName>
    <label>Data Flow Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce to Epicore</fullName>
                <default>true</default>
                <label>Salesforce to Epicore</label>
            </value>
            <value>
                <fullName>Epicore to Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Data_Integration__c.field-meta.xml
<CustomField>
    <fullName>Data_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Data Integration</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Disable_all_frequencies__c.field-meta.xml
<CustomField>
    <fullName>Disable_all_frequencies__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable all frequencies</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Division_ID__c.field-meta.xml
<CustomField>
    <fullName>Division_ID__c</fullName>
    <label>Division ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/EBizCharge_IsLogEnable__c.field-meta.xml
<CustomField>
    <fullName>EBizCharge_IsLogEnable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EBizCharge IsLogEnable</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/EBizcharge_IsLogErrorEnable__c.field-meta.xml
<CustomField>
    <fullName>EBizcharge_IsLogErrorEnable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EBizcharge IsLogErrorEnable</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/EBizcharge_IsLogExceptionEnable__c.field-meta.xml
<CustomField>
    <fullName>EBizcharge_IsLogExceptionEnable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EBizcharge IsLogExceptionEnable</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/EBizcharge_IsLogInfoEnable__c.field-meta.xml
<CustomField>
    <fullName>EBizcharge_IsLogInfoEnable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EBizcharge IsLogInfoEnable</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/EBizcharge_IsLogWarningEnable__c.field-meta.xml
<CustomField>
    <fullName>EBizcharge_IsLogWarningEnable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EBizcharge IsLogWarningEnable</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/EBizcharge_Sync_Accounts_OnInstall__c.field-meta.xml
<CustomField>
    <fullName>EBizcharge_Sync_Accounts_OnInstall__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EBizcharge Sync Accounts OnInstall</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/EBizcharge_Sync_Contacts_OnInstall__c.field-meta.xml
<CustomField>
    <fullName>EBizcharge_Sync_Contacts_OnInstall__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EBizcharge Sync Contacts OnInstall</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Email_Pending_Req_Filter_By__c.field-meta.xml
<CustomField>
    <fullName>Email_Pending_Req_Filter_By__c</fullName>
    <defaultValue>&apos;pastweek&apos;</defaultValue>
    <label>Email Pending Req Filter By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Past Week</fullName>
                <default>true</default>
                <label>Past Week</label>
            </value>
            <value>
                <fullName>Past Month</fullName>
            </value>
            <value>
                <fullName>Past Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Enable_all_frequencies__c.field-meta.xml
<CustomField>
    <fullName>Enable_all_frequencies__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable all frequencies</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Payments_Tab__c.field-meta.xml
<CustomField>
    <fullName>Payments_Tab__c</fullName>
    <defaultValue>&apos;Sale&apos;</defaultValue>
    <label>Payments Tab</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>AuthOnly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Security_Token__c.field-meta.xml
<CustomField>
    <fullName>Security_Token__c</fullName>
    <label>Security Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Sync_Accounts_Filter_By__c.field-meta.xml
<CustomField>
    <fullName>Sync_Accounts_Filter_By__c</fullName>
    <defaultValue>&apos;Past Week&apos;</defaultValue>
    <label>Sync Accounts Filter By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Past Week</fullName>
                <default>true</default>
                <label>Past Week</label>
            </value>
            <value>
                <fullName>Past Month</fullName>
            </value>
            <value>
                <fullName>Past Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Sync_Orders_Filter_By__c.field-meta.xml
<CustomField>
    <fullName>Sync_Orders_Filter_By__c</fullName>
    <defaultValue>&apos;Past Week&apos;</defaultValue>
    <label>Sync Orders Filter By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Past Week</fullName>
                <default>true</default>
                <label>Past Week</label>
            </value>
            <value>
                <fullName>Past Month</fullName>
            </value>
            <value>
                <fullName>Past Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Sync_Recurring_Payment_Filter_By__c.field-meta.xml
<CustomField>
    <fullName>Sync_Recurring_Payment_Filter_By__c</fullName>
    <label>Sync Recurring Payment Filter By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Next Week</fullName>
            </value>
            <value>
                <fullName>Next Month</fullName>
            </value>
            <value>
                <fullName>Next Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Transaction_Filter_By__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Filter_By__c</fullName>
    <defaultValue>&apos;Past Week&apos;</defaultValue>
    <label>Transaction Filter By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Past Week</fullName>
                <default>true</default>
                <label>Past Week</label>
            </value>
            <value>
                <fullName>Past Month</fullName>
            </value>
            <value>
                <fullName>Past Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Use_Custom_Opportunity_Amount__c.field-meta.xml
<CustomField>
    <fullName>Use_Custom_Opportunity_Amount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Custom Opportunity Amount</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/classes/eBc_SettingController.cls
public with sharing class eBc_SettingController {
    public static string ClassName = 'eBc_SettingController';
    public static string MethodName = Configuration.EMPTYSTRING;
    public static ebizchargeServicemodelSoap.eBizService ebiz = new ebizchargeServicemodelSoap.eBizService();
    @AuraEnabled
    public static EBizcharge_Setting__c getSettingsApxc() {
        DML dml = new DML();
        if (test.isRunningTest()) {
            dml = (DML) MockUtil.createMock(DML.class);
        }
        EBC_Logger ebcLogger = new EBC_Logger();
        EBizcharge_Setting__c reciprocate = getSettingsApxc(dml, ebcLogger);
        ebcLogger.saveLogs();
        return reciprocate;
    }
    public static EBizcharge_Setting__c getSettingsApxc(DML dml, EBC_Logger ebcLogger) {
        MethodName = 'getSettingsApxc';
        ebcLogger.debug(ClassName, MethodName, '<<CheckingSettingsF');
        EBizcharge_Setting__c settingsEntity = new EBizcharge_Setting__c();
        String querySelect = 'SELECT AutoPay_bi_annually__c,AutoPay_four_week__c,' +
            'AutoPay_annually__c,AutoPay_bi_weekly__c,AutoPay_quarterly__c,' +
            'AutoPay_weekly__c,AutoPay_bi_monthly__c,AutoPay_daily__c,AutoPay_monthly__c,' +
            'Enable_all_frequencies__c,Disable_all_frequencies__c,' +
            'EBizCharge_IsLogEnable__c,EBizcharge_IsLogErrorEnable__c,EBizcharge_IsLogInfoEnable__c,EBizcharge_IsLogWarningEnable__c,EBizcharge_IsLogExceptionEnable__c,' +
            'Auto_Upload_Order__c,Auto_Upload_Account__c,Auto_Upload_Contact__c,Auto_Upload_Opportunity__c,' +
            'Auto_Upload_Quote__c,EBizcharge_Sync_Accounts_OnInstall__c,EBizcharge_Sync_Contacts_OnInstall__c,' +
            'Division_ID__c,Data_Flow_Direction__c,Application_ID__c,Sync_Recurring_Payment_Filter_By__c,Payments_Tab__c,' +
            'Data_Integration__c,Use_Custom_Opportunity_Amount__c,Id,Security_Token__c,User_Name__c,Password__c,' +
            'Transaction_Filter_By__c,Email_Pending_Req_Filter_By__c,Sync_Orders_Filter_By__c,' +
            'Sync_Accounts_Filter_By__c,Sync_Products_Filter_By__c,Allow_Partial_Payment__c,Allow_Order_Payment_Type__c,' +
            'Allow_Opportunity_Payment_Type__c,Allow_Quote_Payment_Type__c,Show_Tax_Field__c,Tax_Action__c,Tax_Calculate_By__c,' +
            'Tax_Manual_Type__c,Tax_Default_Percent__c,' +
            'Auto_Upload_Product__c,Auto_Apply_Received_Payment__c,' +
            'Component_Label__c,Currency__c,Ebizcharge_Transaction_Last_Sync_Date__c,Ebizcharge_Product_Last_Sync_Date__c,Ebizcharge_Accounts_Last_Sync_Date__c,Ebizcharge_Orders_Last_Sync_Date__c';
        String queryFrom = 'FROM EBizcharge_Setting__c';
        String queryWhere = Configuration.EMPTYSTRING;
        String queryOrderby = 'Order by CreatedDate DESC';
        try {
            settingsEntity = (EBizcharge_Setting__c) dml.selectSingleRecord(querySelect, queryFrom, Configuration.EMPTYSTRING, Configuration.EMPTYSTRING, queryOrderby);
        } catch (Exception e) {
            ebcLogger.debug(ClassName, MethodName, e.getMessage(), Configuration.EXCEPTIONLOGTYPE);
        }
        return settingsEntity;
    }
    @AuraEnabled
    public static String runTransactionsJob() {
        System.schedule('Scheduled Job 1', '0 0 * * * ?', new TransactionsShedulable());
        System.schedule('Scheduled Job 2', '0 10 * * * ?', new TransactionsShedulable());
        System.schedule('Scheduled Job 3', '0 20 * * * ?', new TransactionsShedulable());
        System.schedule('Scheduled Job 4', '0 30 * * * ?', new TransactionsShedulable());
        System.schedule('Scheduled Job 5', '0 40 * * * ?', new TransactionsShedulable());
        System.schedule('Scheduled Job 6', '0 50 * * * ?', new TransactionsShedulable());
        return Configuration.SUCCESSMESSAGE;
    }
    @AuraEnabled
    public static String getApplicationDataApxc(String applicationID, String lookupID) {
        MethodName = 'getApplicationDataApxc';
        EBC_Logger ebcLogger = new EBC_Logger();
        ebizchargeServicemodelSoap.ApplicationData applicationData;
        String payload = Configuration.EMPTYSTRING;
        try {
            applicationData = ebiz.getApplicationData(applicationID, lookupID, Configuration.EMPTYSTRING);
            Blob payloadBlob = EncodingUtil.base64Decode(applicationData.Base64ParametersString);
            payload = payloadBlob.toString();
        } catch (Exception e) {
            ebcLogger.debug(ClassName, MethodName, e.getMessage(), Configuration.EXCEPTIONLOGTYPE);
        }
        return payload;
    }
    @AuraEnabled
    public static String saveSettingsApxc(EBizcharge_Setting__c Settings) {
        DML dml = new DML();
        if (test.isRunningTest()) {
            dml = (DML) MockUtil.createMock(DML.class);
        }
        EBC_Logger ebcLogger = new EBC_Logger();
        String reciprocate = saveSettingsApxc(dml, Settings, ebcLogger);
        ebcLogger.saveLogs();
        return reciprocate;
    }
    public static String saveSettingsApxc(DML dml, EBizcharge_Setting__c Settings, EBC_Logger ebcLogger) {
        MethodName = 'saveSettingsApxc';
        try {
            if (Settings.Tax_Action__c == 'Tax Included') {
                ebizchargeServicemodelSoap.MerchantTransactionData response;
                response = ebiz.GetMerchantTransactionData(eBc_UtilityController.getSecurityToken(dml, ebcLogger));
                Settings.Tax_Default_Percent__c = response.TaxPercentage.setScale(2, RoundingMode.CEILING);
            }
            dml.upsertRecord(Settings, 'EBizcharge_Setting__c.Id');
            //dml.upsertRecord(Settings, 'Ebiz_C__EBizcharge_Setting__c.Id');
        } catch (Exception e) {
            ebcLogger.debug(ClassName, MethodName, e.getMessage(), Configuration.EXCEPTIONLOGTYPE);
        }
        return Configuration.SUCCESSMESSAGE;
    }
    @AuraEnabled
    public static List < EBizcharge_Setting__c > getSettingsList() {
        DML dml = new DML();
        if (test.isRunningTest()) {
            dml = (DML) MockUtil.createMock(DML.class);
        }
        EBC_Logger ebcLogger = new EBC_Logger();
        List < EBizcharge_Setting__c > reciprocate = getSettingsList(dml, ebcLogger);
        ebcLogger.saveLogs();
        return reciprocate;
    }
    public static List < EBizcharge_Setting__c > getSettingsList(DML dml, EBC_Logger ebcLogger) {
        MethodName = 'getSettingsList';
        List < EBizcharge_Setting__c > settingsList = new List < EBizcharge_Setting__c > ();
        try {
            String querySelect = 'SELECT id, Name,Security_Token__c, User_Name__c, Password__c';
            String queryFrom = 'FROM EBizcharge_Setting__c';
            settingsList = (List < EBizcharge_Setting__c > ) dml.selectRecords(querySelect, queryFrom, Configuration.EMPTYSTRING, Configuration.EMPTYSTRING, Configuration.EMPTYSTRING, Configuration.EMPTYSTRING);
        } catch (Exception e) {
            ebcLogger.debug(ClassName, MethodName, e.getMessage(), Configuration.EXCEPTIONLOGTYPE);
        }
        return settingsList;
    }
    @AuraEnabled
    public static EBizcharge_Setting__c getSettingRecord(String recID) {
        DML dml = new DML();
        if (test.isRunningTest()) {
            dml = (DML) MockUtil.createMock(DML.class);
        }
        EBC_Logger ebcLogger = new EBC_Logger();
        EBizcharge_Setting__c reciprocate = getSettingRecord(dml, recID, ebcLogger);
        ebcLogger.saveLogs();
        return reciprocate;
    }
    public static EBizcharge_Setting__c getSettingRecord(DML dml, String recID, EBC_Logger ebcLogger) {
        MethodName = 'getSettingRecord';
        EBizcharge_Setting__c settingsEntity = new EBizcharge_Setting__c();
        try {
            String querySelect = 'SELECT id, Name, Security_Token__c, User_Name__c, Password__c';
            String queryFrom = 'FROM EBizcharge_Setting__c';
            String queryWhere = 'where Id = \'' + recID + '\'';
            settingsEntity = (EBizcharge_Setting__c) dml.selectSingleRecord(querySelect, queryFrom, queryWhere, Configuration.EMPTYSTRING, Configuration.EMPTYSTRING);
        } catch (Exception e) {
            ebcLogger.debug(ClassName, MethodName, e.getMessage(), Configuration.EXCEPTIONLOGTYPE);
        }
        return settingsEntity;
    }
    @AuraEnabled
    public static List < Map < String, String >> getListOfEmailTemplates() {
        DML dml = new DML();
        if (test.isRunningTest()) {
            dml = (DML) MockUtil.createMock(DML.class);
        }
        EBC_Logger ebcLogger = new EBC_Logger();
        List < Map < String, String >> reciprocate = getListOfEmailTemplates(dml, ebcLogger);
        ebcLogger.saveLogs();
        return reciprocate;
    }
    public static List < Map < String, String >> getListOfEmailTemplates(DML dml, EBC_Logger ebcLogger) {
        MethodName = 'getListOfEmailTemplates';
        List < Map < String, String >> returnEmailTemplates = new List < Map < String, String >> ();
        returnEmailTemplates.add(new Map < String, String > {
            'value' => Configuration.EMPTYSTRING,
            'label' => 'None'
        });
        ebizchargeServicemodelSoap.ArrayOfEmailTemplate emailTemplateResponse = new ebizchargeServicemodelSoap.ArrayOfEmailTemplate();
        ebizchargeServicemodelSoap.EmailTemplate[] ebizEmailTemplates;
        try {
            emailTemplateResponse = ebiz.GetEmailTemplates(eBc_UtilityController.getSecurityToken(dml, ebcLogger), Configuration.EMPTYSTRING, Configuration.EMPTYSTRING);
            ebizEmailTemplates = emailTemplateResponse.EmailTemplate;
            if (ebizEmailTemplates != null) {
                for (ebizchargeServicemodelSoap.EmailTemplate emailTemplate: ebizEmailTemplates) {
                    returnEmailTemplates.add(new Map < String, String > {
                        'value' => emailTemplate.TemplateInternalId,
                        'label' => emailTemplate.TemplateName
                    });
                }
            }
        } catch (Exception e) {
            ebcLogger.debug(ClassName, MethodName, e.getMessage(), Configuration.EXCEPTIONLOGTYPE);
        }
        return returnEmailTemplates;
    }
}