SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/EBizcharge_Setting__c.object-meta.xml
<CustomObject>
    <label>EBizcharge Setting</label>
    <nameField>
        <label>EBizcharge Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBizcharge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Division_ID__c.field-meta.xml
<CustomField>
    <fullName>Division_ID__c</fullName>
    <label>Division ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/classes/test_ebc_ProductAddorUpdateFlow.cls
@isTest
public with sharing class test_ebc_ProductAddorUpdateFlow {
    @isTest(OnInstall = true)
    public static void testMethod1() {
        DML dml = (DML) MockUtil.createMock(DML.class);
        product2 prod = StaticMockData.getProduct2()[0];
        prod.EBizCharge_Internal_ID__c = '111111';
        prod.Name = 'Test Prod';
        prod.Description = 'Test Product Entry';
        prod.productCode = 'ABCD';
        prod.isActive = true;
        PricebookEntry pbookE = StaticMockData.getPricebookEntry()[0];
        EBizcharge_Setting__c settings = new EBizcharge_Setting__c();
        settings.Ebiz_C__Auto_Upload_Product__c = true;
        settings.Division_ID__c = '1234';
        insert settings;
        ProductAddorUpdateFlow.invoke_updateProduct(New product2[] {
            prod
        });
        ProductAddorUpdateFlow.invoke_updateProduct(dml, prod);
        string processStrMap = '{"saveACH":true, "saveCard":true, "AccountId" : "' + prod.Id + '", "Name": "Test", "Description":"TestDescription", "ProductCode" : "t2222", "IsActive" : true, "SendReceiptTo": true, "addEmails" : "test@test.com" }';
        ProductAddorUpdateFlow.invoke_AddProductFuture(processStrMap, '1111111', '8');
        ProductAddorUpdateFlow.invoke_AddProduct(dml, prod);
    }
}