SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/EBizcharge_Setting__c.object-meta.xml
<CustomObject>
    <label>EBizcharge Setting</label>
    <nameField>
        <label>EBizcharge Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBizcharge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Component_Label__c.field-meta.xml
<CustomField>
    <fullName>Component_Label__c</fullName>
    <label>Component Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Email_Pending_Req_Filter_By__c.field-meta.xml
<CustomField>
    <fullName>Email_Pending_Req_Filter_By__c</fullName>
    <defaultValue>&apos;pastweek&apos;</defaultValue>
    <label>Email Pending Req Filter By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Past Week</fullName>
                <default>true</default>
                <label>Past Week</label>
            </value>
            <value>
                <fullName>Past Month</fullName>
            </value>
            <value>
                <fullName>Past Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Security_Token__c.field-meta.xml
<CustomField>
    <fullName>Security_Token__c</fullName>
    <label>Security Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Sync_Accounts_Filter_By__c.field-meta.xml
<CustomField>
    <fullName>Sync_Accounts_Filter_By__c</fullName>
    <defaultValue>&apos;Past Week&apos;</defaultValue>
    <label>Sync Accounts Filter By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Past Week</fullName>
                <default>true</default>
                <label>Past Week</label>
            </value>
            <value>
                <fullName>Past Month</fullName>
            </value>
            <value>
                <fullName>Past Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Sync_Orders_Filter_By__c.field-meta.xml
<CustomField>
    <fullName>Sync_Orders_Filter_By__c</fullName>
    <defaultValue>&apos;Past Week&apos;</defaultValue>
    <label>Sync Orders Filter By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Past Week</fullName>
                <default>true</default>
                <label>Past Week</label>
            </value>
            <value>
                <fullName>Past Month</fullName>
            </value>
            <value>
                <fullName>Past Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Sync_Products_Filter_By__c.field-meta.xml
<CustomField>
    <fullName>Sync_Products_Filter_By__c</fullName>
    <defaultValue>&apos;Past Week&apos;</defaultValue>
    <label>Sync Products Filter By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Past Week</fullName>
                <default>true</default>
                <label>Past Week</label>
            </value>
            <value>
                <fullName>Past Month</fullName>
            </value>
            <value>
                <fullName>Past Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Tax_Action__c.field-meta.xml
<CustomField>
    <fullName>Tax_Action__c</fullName>
    <defaultValue>&apos;Tax Included&apos;</defaultValue>
    <label>Tax Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tax Included</fullName>
                <default>true</default>
                <label>Tax Included</label>
            </value>
            <value>
                <fullName>Tax Calculate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Tax_Calculate_By__c.field-meta.xml
<CustomField>
    <fullName>Tax_Calculate_By__c</fullName>
    <label>Tax Calculate By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Tax_Default_Percent__c.field-meta.xml
<CustomField>
    <fullName>Tax_Default_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Tax Default Percent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Tax_Manual_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Manual_Type__c</fullName>
    <label>Tax Manual Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Use Percent</fullName>
            </value>
            <value>
                <fullName>Use Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Transaction_Filter_By__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Filter_By__c</fullName>
    <defaultValue>&apos;Past Week&apos;</defaultValue>
    <label>Transaction Filter By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Past Week</fullName>
                <default>true</default>
                <label>Past Week</label>
            </value>
            <value>
                <fullName>Past Month</fullName>
            </value>
            <value>
                <fullName>Past Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFQBD/Ebiz/force-app/main/default/classes/test_UpdateSettings.cls
@isTest
public  class test_UpdateSettings {

    @isTest(OnInstall=true)
    public static void testMethod1() {
        Integer len         = 10; //fake id
        Blob blobKey        = crypto.generateAesKey(128);
        String key          = EncodingUtil.convertToHex(blobKey);
        String reg          = key.substring(0,len);
        
        EBizcharge_Setting__c  ES = new EBizcharge_Setting__c();
        ES.Security_Token__c        = reg;
        ES.User_Name__c             = 'test-1';
        ES.Password__c              = '123';
        ES.Transaction_Filter_By__c  = 'Today ';
        ES.Email_Pending_Req_Filter_By__c  = 'Today ';
        ES.Sync_Orders_Filter_By__c  = 'Today';
        ES.Sync_Accounts_Filter_By__c  = 'Today';
        ES.Sync_Products_Filter_By__c  = 'Today';
        ES.Tax_Action__c  = 'Today';
        ES.Tax_Calculate_By__c  = 'Auto';
        ES.Tax_Manual_Type__c =  'Use Percent';
        ES.Tax_Default_Percent__c =  1;
        ES.Component_Label__c =  'test';
        ES.Tax_Action__c  = 'Tax Included';
        system.assertEquals('test-1', ES.User_Name__c);
        insert ES;
        delete ES;
    }
}