SFQBD/Ebiz/force-app/main/default/objects/Account/fields/EBizCharge_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>EBizCharge_Internal_ID__c</fullName>
    <label>EBizCharge Internal ID Account</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/EBizcharge_Setting__c.object-meta.xml
<CustomObject>
    <label>EBizcharge Setting</label>
    <nameField>
        <label>EBizcharge Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBizcharge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Auto_Upload_Account__c.field-meta.xml
<CustomField>
    <fullName>Auto_Upload_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If value true, Account will auto upload on gateway upon creation or modification</description>
    <inlineHelpText>If value true, Account will auto upload on gateway upon creation or modification</inlineHelpText>
    <label>Auto Upload Account</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Security_Token__c.field-meta.xml
<CustomField>
    <fullName>Security_Token__c</fullName>
    <label>Security Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/classes/test_EBC_AccountInsertOrUpdateApexFlow.cls
@isTest
public class test_EBC_AccountInsertOrUpdateApexFlow {
    public static testMethod void doTest() {
        Account acc = StaticMockData.getAccount()[0];
        EBC_Logger ebcLogger = new EBC_Logger();
        String myJSON = JSON.serialize(acc);
        DML dml = (DML) MockUtil.createMock(DML.class);
        EBizcharge_Setting__c settings = new EBizcharge_Setting__c();
        settings.Security_Token__c = 'reg';
        settings.User_Name__c = 'test-1';
        settings.Password__c = 'test-1';
        settings = eBc_SettingController.getSettingsApxc(dml, ebcLogger);
        settings.Auto_Upload_Account__c = true;
        insert settings;
        AccountInsertOrUpdateApexFlow.invoke_updateAccount(New List<AccountInsertOrUpdateApexFlow.AccountWrapper>());
        AccountInsertOrUpdateApexFlow.invoke_UpdateAccountFuture(myJSON,'1212341');
    }
    public static testMethod void doTest1() {
        Account acc = StaticMockData.getAccount()[0];
        acc.EBizCharge_Internal_ID__c = null;
        EBC_Logger ebcLogger = new EBC_Logger();
        String myJSON = JSON.serialize(acc);
        DML dml = (DML) MockUtil.createMock(DML.class);
        EBizcharge_Setting__c settings = new EBizcharge_Setting__c();
        settings.Security_Token__c = 'reg';
        settings.User_Name__c = 'test-1';
        settings.Password__c = 'test-1';
        settings = eBc_SettingController.getSettingsApxc(dml, ebcLogger);
        settings.Auto_Upload_Account__c = true;
        insert settings;
        AccountInsertOrUpdateApexFlow.invoke_updateAccount(New List<AccountInsertOrUpdateApexFlow.AccountWrapper>());
        AccountInsertOrUpdateApexFlow.invoke_AddAccountFuture(acc.Id);
        try {
            AccountInsertOrUpdateApexFlow.invoke_updateAccount(New List<AccountInsertOrUpdateApexFlow.AccountWrapper>());
            AccountInsertOrUpdateApexFlow.invoke_AddAccountFuture(null);
        } catch (DmlException e) {}
    }
}