SFQBD/Ebiz/force-app/main/default/objects/Account/fields/EBizCharge_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>EBizCharge_Internal_ID__c</fullName>
    <label>EBizCharge Internal ID Account</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/EBizcharge_Setting__c.object-meta.xml
<CustomObject>
    <label>EBizcharge Setting</label>
    <nameField>
        <label>EBizcharge Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBizcharge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFQBD/Ebiz/force-app/main/default/objects/EBizcharge_Setting__c/fields/Auto_Upload_Account__c.field-meta.xml
<CustomField>
    <fullName>Auto_Upload_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If value true, Account will auto upload on gateway upon creation or modification</description>
    <inlineHelpText>If value true, Account will auto upload on gateway upon creation or modification</inlineHelpText>
    <label>Auto Upload Account</label>
    <type>Checkbox</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/classes/AccountInsertOrUpdateApexFlow.cls
public with sharing class AccountInsertOrUpdateApexFlow {
    public static string ClassName = 'AccountInsertOrUpdateApexFlow';
    public static string MethodName = Configuration.EMPTYSTRING;
    @InvocableMethod
    public static void invoke_updateAccount(List < AccountWrapper > accounts) {
        MethodName = 'invoke_updateAccount';
        EBC_Logger ebcLogger = new EBC_Logger();
        ebcLogger.debug(ClassName, MethodName, 'accounts are ' + accounts);
        Dml dml = new Dml();
        try {
            EBizcharge_Setting__c settings = new EBizcharge_Setting__c();
            settings = eBc_SettingController.getSettingsApxc(dml, ebcLogger);
            if (settings.Auto_Upload_Account__c) {
                for (AccountWrapper account: accounts) {
                    if (account.accountRecord.EBizCharge_Internal_ID__c != null) {
                        String accountString = json.serialize(account.accountRecord);
                        String Old_Qbd_Id = account.Old_Qbd_Id;
                        invoke_UpdateAccountFuture(accountString,Old_Qbd_Id);
                    } else {
                        invoke_AddAccountFuture(account.accountRecord.Id);
                    }
                }
            }
        } catch (Exception e) {
            ebcLogger.debug(ClassName, MethodName, e.getMessage(), Configuration.EXCEPTIONLOGTYPE);
        }
    }
    public class AccountWrapper{   
        @InvocableVariable
        public String Old_Qbd_Id;
        @InvocableVariable
        public Account accountRecord;
    }
    @Future(callout = true)
    public static void invoke_AddAccountFuture(string accountId) {
        MethodName = 'invoke_AddAccountFuture';
        DML dml = new DML();
        EBC_Logger ebcLogger = new EBC_Logger();
        try {
            EBC_ComponentController.getDetailApxc(dml, accountId, string.valueOf(Enums.SALESFORCEOBJECTNAMES.Account), ebcLogger);
        } catch (Exception e) {
            ebcLogger.debug(ClassName, MethodName, e.getMessage(), Configuration.EXCEPTIONLOGTYPE);
        }
    }
    @Future(callout = true)
    public static void invoke_UpdateAccountFuture(string accountString,string OldId) {
        MethodName = 'invoke_UpdateAccountFuture';
        EBC_Logger ebcLogger = new EBC_Logger();
        DML dml = new DML();
        try {
            Account account = (Account) Json.deserialize(accountString, Account.class);
            //SF-Qbd
            eBc_UtilityController.invoke_addORUpdCustomerQBD(dml, account, eBc_UtilityController.getSecurityToken(dml, ebcLogger),OldId,string.valueOf(Enums.ENTITYACTIONS.updateCustomer), ebcLogger);
        } catch (Exception e) {
            ebcLogger.debug(ClassName, MethodName, e.getMessage(), Configuration.EXCEPTIONLOGTYPE);
        }
    }
}