SFQBD/Ebiz/force-app/main/default/objects/Order/fields/EBizCharge_Order_Balance__c.field-meta.xml
<CustomField>
    <fullName>EBizCharge_Order_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>EBizCharge Order Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/objects/Order/fields/EBizCharge_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>EBizCharge_Order_Status__c</fullName>
    <label>EBizCharge Order Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

SFQBD/Ebiz/force-app/main/default/classes/customLookUpController.cls
public class customLookUpController {
    
    //this class is deprected*
    @AuraEnabled
    public static List < sObject > fetchLookUpValues(String searchKeyWord, String ObjectName) {
       /*
        system.debug('ObjectName-->' + ObjectName);
        String searchKey = '';
        String condition = '';
        String Fields = '';
        if(ObjectName == 'account'){
            Fields = 'Name';
            if(searchKeyWord != null && searchKeyWord !=''){
                searchKey = searchKeyWord + '%';
                condition =  'WHERE Name LIKE: searchKey';
            }
        }else if (ObjectName == 'Order'){
            Fields = 'OrderNumber';
            if(searchKeyWord != null && searchKeyWord !=''){
                searchKey = searchKeyWord + '%';
                condition =  'WHERE OrderNumber LIKE: searchKey AND EBizCharge_Order_Status__c <> \'Paid\' AND TotalAmount > 0 '; //AND (EBizCharge_Order_Balance__c = null OR EBizCharge_Order_Balance__c > 0)
            }else{
                condition =  'WHERE EBizCharge_Order_Status__c <> \'Paid\' AND TotalAmount > 0 '; //AND (EBizCharge_Order_Balance__c = null OR EBizCharge_Order_Balance__c > 0)
            }
        }
        
        List < sObject > returnList = new List < sObject > ();
        
        // Create a Dynamic SOQL Query For Fetch Record List with LIMIT 5   
        String sQuery =  'SELECT Id,'+Fields+' FROM ' +ObjectName+' '+condition+' order by createdDate DESC limit 10';
        system.debug('sQuery>>>'+sQuery);
        List < sObject > lstOfRecords = Database.query(sQuery);
        
        for (sObject obj: lstOfRecords) {
            returnList.add(obj);
        }
        return returnList;
*/
        return null;
    }
}